### ISSUE TITLE
Tests fail on Python 3.13: uses unittest.makeSuite()

### ISSUE THREAD

**Issue by stefanor** [cracklib/cracklib#103]
https://docs.python.org/3.13/whatsnew/3.13.html#unittest

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import cracklib; cracklib.test(dictpath="/<<PKGBUILDDIR>>/debian/tmp/cracklib_dict")
                     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<<PKGBUILDDIR>>/debian/buildtmp/python3.13/python/build/lib.linux-aarch64-cpython-313/cracklib.py", line 225, in test
    result = test_cracklib.run(verbosity=verbosity, repeat=repeat, use_dictpath=dictpath)
  File "/<<PKGBUILDDIR>>/debian/buildtmp/python3.13/python/build/lib.linux-aarch64-cpython-313/test_cracklib.py", line 144, in run
    suite.addTest(unittest.makeSuite(cls))
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/unittest/__init__.py", line 80, in __getattr__
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
AttributeError: module 'unittest' has no attribute 'makeSuite'
```

**Comment by jandd** [comment]
may need to be replaced with https://docs.python.org/3.13/library/unittest.html#unittest.TestLoader.loadTestsFromTestCase which should work since Python 3.7. Now that CentOS/RHEL 6, which came with Python 3.6, are EOL this could be changed.

**Comment by stefanor** [comment]
Patch added in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1081425#14

**Comment by nneul** [comment]
Thank you @pinotree
